Task1
ivanov-kir-m/Playlist_Maker pull request #1
Opened 2023-05-26 07:30 UTC by ivanov-kir-m

Task Sprint 8

2023-05-27 19:41 UTC, NoDopezzz requested changes

2023-05-27 19:41 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/MainActivity.kt
> +            toastAmBtnFindId.show()
⚠️ Стоит сразу поменять показы `Toast` на переходы к соответствующим `Activity`

2023-05-27 19:41 UTC, NoDopezzz commented on app/src/main/res/drawable/music.xml
> +      android:fillColor="#1A1B22"/>
💡 Цвета в векторных изображениях также можно выносить в файл ресурсов. Так, можно организовать более гибкую дизайн-систему приложения.
Кроме того, это поможет экономить занимаемое ресурсами место, если нам нужно иметь иконки разных цветов для разных тем приложения. Ведь вместо того, чтобы создавать две иконки и класть в `drawable` и `drawable-night`, мы можем создать одну иконку в drawable, а файл ресурса с цветом будет задан в `values` и `values-night`.

Подробнее различные темы приложения нами будут рассмотрены в следующем спринте.

2023-05-27 19:41 UTC, NoDopezzz commented on app/src/main/res/layout/activity_main.xml
> +        app:iconPadding="10dp"
⚠️ `iconPadding` используется сразу для трех кнопок, поэтому это значение стоит вынести в `dimens`

2023-05-27 19:41 UTC, NoDopezzz commented on app/src/main/res/layout/activity_settings.xml
> +            android:layout_width="wrap_content"
⏫ Вместо связки `TextView` + `ImageView` внутри `FrameLayout` можно воспользоваться `AppCompatTextView` и установкой аттрибута `android:drawableEnd` для задания иконки перед текстом. Таким образом
- будет меньше кода
- мы избавляемся от лишней вложенности `View`

💡 Стоит помнить, что лишняя вложенность при построении макетов [отрицательно сказывается](https://developer.android.com/topic/performance/rendering/optimizing-view-hierarchies#removing) на скорости отрисовки экрана, а значит и на производительности. Стоит всегда стараться делать верстку максимально плоской для лучшей производительности.

2023-05-27 19:41 UTC, NoDopezzz commented on app/src/main/res/values-en/strings.xml
> +<resources>
👍 Отличная идея поддерживать мультиязычность!

2023-05-27 19:41 UTC, NoDopezzz commented on app/src/main/res/values/demens.xml
> +    <dimen name="am_btn_margin_left_right">17sp</dimen>
⚠️ Стоит помнить разницу между sp и dp:
- **dp** является единицей размера экрана основанной на его физической плотности. Чем больше плотность экрана, тем больше пикселей будет занимать один `dp`.
- **sp** является единицей по своей сути схожей с dp, но она зависит не только от плотности экрана, но и от пользовательских настроек устройства. 
Например, ты можешь сходить в настройки устройства и поменять размер шрифта. Тогда можно увидеть, что элементы, размеры которых были в sp также изменились. Поэтому `sp` обычно применяют только для текста.

2023-05-28 17:08 UTC, ivanov-kir-m commented on app/src/main/java/com/practicum/playlistmaker/MainActivity.kt
> +            toastAmBtnFindId.show()
Эм, в 8-м спринте должно быть только 2 activity: главная и настройки, возможно дальше будут замены но на текущий момент по ТЗ такого не требуется, кажется

2023-05-29 17:24 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/MainActivity.kt
> +            toastAmBtnFindId.show()
В критериях как раз описаны пункты про эти два новых экрана. Пока мы действительно оставляем их пустыми и в дальнейшем будем улучшать.

Увидел, что ты в последних коммитах добавил эти Activity - **Approved** ✅

2023-06-05 11:25 UTC, merged